INSERT INTO BusinessTypes (BusinessTypeName)
VALUES
('Araç Kiralama'),
('Ayakkabı / Lostra'),
('Aydınlatma'),
('Bakkal / Market'),
('Bar'),
('Beyaz Eşya'),
('Giyim'),
('Elektronik'),
('Kuaför / Berber'),
('Restoran / Kafe'),
('Emlak'),
('Mobilya'),
('Eğitim Kurumu'),
('Sağlık Hizmetleri'),
('Spor Salonu'),
('Oto Tamir / Servis'),
('Tarım / Hayvancılık'),
('Tekstil'),
('İnşaat'),
('Kozmetik'),
('Çiçekçi'),
('Pastane / Fırın'),
('Kırtasiye'),
('Seyahat Acentesi'),
('Diğer');
