INSERT INTO BusinessTypes (BusinessTypeName)
VALUES
('Unknown'),
('Akaryakıt/enerji istasyonu'),
('Ambalaj Malzemeleri'),
('Araç Kiralama'),
('Ayakkabı/ Lostra'),
('Aydınlatma'),
('Bakkal/Market'),
('Bar'),
('Beyaz Eşya'),
('Börekçi'),
('Büfe'),
('Cep Telefonu'),
('Depo'),
('Diğer'),
('Dondurmacı'),
('Dönerci'),
('Döviz Bürosu'),
('Dövme Stüdyosu'),
('Eczane'),
('Elektrik / Uydu Sist.'),
('Elektronik Eşya'),
('Emlak Ofisi'),
('Esnaf Lokantası'),
('Ev Dekorasyonu'),
('Fotoğraf Stüdyosu'),
('Fırın'),
('GSM Bayi'),
('Ganyan'),
('Giyim Mağazası'),
('Hobi Malzemeleri'),
('Hukuk Bürosu'),
('Hırdavat'),
('Kafe'),
('Kahvaltı Salonu'),
('Kahveci'),
('Kantin'),
('Kasap'),
('Kebap'),
('Kitap Mağazası'),
('Kişisel Bakım'),
('Kokoreççi'),
('Kozmetik / Parfümeri'),
('Kuaför (Bayan)'),
('Kuaför (Erkek)'),
('Kuaför (Kadın/Erkek)'),
('Kuruyemiş / Baharat'),
('Kuyumcu'),
('Kıraathane'),
('Kırtasiye'),
('Manav'),
('Marangoz'),
('Mefruşatçı'),
('Mobilya'),
('Muhasebeci'),
('Nalbur'),
('Optik ve Gözlük'),
('Oto Ekspertiz'),
('Oto Tamir / Lastik / Aksesuar'),
('Oto Yıkama'),
('Otopark'),
('Oyun Kafe'),
('Oyuncak ve Hediyelik'),
('Parti Malzemeleri'),
('Pastane'),
('Pet Shop'),
('Pide Lahmacun'),
('Pilates Stüdyosu'),
('Reklam / Baskı'),
('Resim Atölyesi'),
('Restoran'),
('Sanat Kursu'),
('Sanat Sergisi'),
('Sağlık Kliniği'),
('Sinema Salonu'),
('Soba/Mangal/Şömine'),
('Spor Mağazası'),
('Spor Salonu'),
('Su Bayi'),
('Süper Market'),
('Taksi Durağı'),
('Takı Aksesuar'),
('Tamirhane'),
('Tantunici'),
('Tarım Malzemeleri'),
('Tekel Bayi'),
('Terzi'),
('Tesisatçı'),
('Tüp Bayi'),
('Çiçekçi'),
('Çiğ Köfteci'),
('Ödeme Noktası'),
('İnternet Kafe'),
('Şans Oyunları'),
('Şarküteri');